type iconMetadataType = {
  [iconName: string]: {
    category: "Action" | "Content" | "Decorative" | "Product";
  };
};

export const iconMetadata: iconMetadataType = {
  /**************
   * Core Icons *
   **************/
  //Action
  ArrowBackIcon: { category: "Action" },
  ArrowForwardIcon: { category: "Action" },
  ChevronDownIcon: { category: "Action" },
  ChevronUpIcon: { category: "Action" },
  CloseIcon: { category: "Action" },
  CopyIcon: { category: "Action" },
  DownloadIcon: { category: "Action" },
  ExpandIcon: { category: "Action" },
  OutboundIcon: { category: "Action" },
  PlusIcon: { category: "Action" },
  SearchIcon: { category: "Action" },
  ShrinkIcon: { category: "Action" },
  TerminalIcon: { category: "Action" },
  // Content
  CheckIcon: { category: "Content" },
  DocsIcon: { category: "Content" },
  InfoIcon: { category: "Content" },
  PhoneIcon: { category: "Content" },
  // Decorative
  AddIcon: { category: "Decorative" },
  AgentIcon: { category: "Decorative" },
  AlarmIcon: { category: "Decorative" },
  AuthenticateIcon: { category: "Decorative" },
  BankIcon: { category: "Decorative" },
  BellIcon: { category: "Decorative" },
  BookIcon: { category: "Decorative" },
  BotIcon: { category: "Decorative" },
  BrainIcon: { category: "Decorative" },
  BuildingIcon: { category: "Decorative" },
  CalendarIcon: { category: "Decorative" },
  CallTrackingIcon: { category: "Decorative" },
  CarIcon: { category: "Decorative" },
  ChartIcon: { category: "Decorative" },
  ChatbotIcon: { category: "Decorative" },
  ChatIcon: { category: "Decorative" },
  CheckedMessageIcon: { category: "Decorative" },
  ClickIcon: { category: "Decorative" },
  CloudIcon: { category: "Decorative" },
  ConnectionIcon: { category: "Decorative" },
  ConsultIcon: { category: "Decorative" },
  ContactCenterIcon: { category: "Decorative" },
  ConversationIcon: { category: "Decorative" },
  CubesIcon: { category: "Decorative" },
  DispatchIcon: { category: "Decorative" },
  EngagementIcon: { category: "Decorative" },
  FingerprintIcon: { category: "Decorative" },
  FireworksIcon: { category: "Decorative" },
  FunnelIcon: { category: "Decorative" },
  GlobalIcon: { category: "Decorative" },
  GlobalSecurityIcon: { category: "Decorative" },
  GlobalSimIcon: { category: "Decorative" },
  HandshakeIcon: { category: "Decorative" },
  HeadphoneIcon: { category: "Decorative" },
  HealthcareIcon: { category: "Decorative" },
  HospitalityIcon: { category: "Decorative" },
  InsuranceIcon: { category: "Decorative" },
  IntegrationIcon: { category: "Decorative" },
  IvrIcon: { category: "Decorative" },
  LegoIcon: { category: "Decorative" },
  MegaphoneIcon: { category: "Decorative" },
  MessageBubbleIcon: { category: "Decorative" },
  MoneyIcon: { category: "Decorative" },
  NotificationIcon: { category: "Decorative" },
  PasswordIcon: { category: "Decorative" },
  PhonebookIcon: { category: "Decorative" },
  PlaneIcon: { category: "Decorative" },
  ProgrammingIcon: { category: "Decorative" },
  RealEstateIcon: { category: "Decorative" },
  RefreshIcon: { category: "Decorative" },
  RetailIcon: { category: "Decorative" },
  SecurityIcon: { category: "Decorative" },
  SimIcon: { category: "Decorative" },
  Smartphone1Icon: { category: "Decorative" }, // known as "Wireless" in Figma
  SmartphoneIcon: { category: "Decorative" },
  SmileIcon: { category: "Decorative" },
  SpaceshipIcon: { category: "Decorative" },
  TeamIcon: { category: "Decorative" },
  TextMessageIcon: { category: "Decorative" },
  TowerIcon: { category: "Decorative" },
  UserHeartIcon: { category: "Decorative" },
  UserSignalIcon: { category: "Decorative" },
  WarningIcon: { category: "Decorative" },
  WifiIcon: { category: "Decorative" },
  // Product
  AddOnsIcon: { category: "Product" },
  AuthyIcon: { category: "Product" },
  AutopilotIcon: { category: "Product" },
  ChannelsIcon: { category: "Product" },
  CliIcon: { category: "Product" },
  ConversationsIcon: { category: "Product" },
  CopilotIcon: { category: "Product" },
  ElasticSipTrunkingIcon: { category: "Product" },
  EmailValidationIcon: { category: "Product" },
  FlexIcon: { category: "Product" },
  FrameIcon: { category: "Product" },
  FunctionsIcon: { category: "Product" },
  InterconnectIcon: { category: "Product" },
  LookupIcon: { category: "Product" },
  MediaStreamsIcon: { category: "Product" },
  NarrowbandIcon: { category: "Product" },
  NotifyIcon: { category: "Product" },
  PayIcon: { category: "Product" },
  PhoneNumbersIcon: { category: "Product" },
  ProgrammableChatIcon: { category: "Product" },
  ProgrammableFaxIcon: { category: "Product" },
  ProgrammableSmsIcon: { category: "Product" },
  ProgrammableVideoIcon: { category: "Product" },
  ProgrammableVoiceIcon: { category: "Product" },
  ProgrammableWirelessIcon: { category: "Product" },
  ProxyIcon: { category: "Product" },
  RuntimeIcon: { category: "Product" },
  SdkIcon: { category: "Product" },
  ShortCodesIcon: { category: "Product" },
  StudioLogoIcon: { category: "Product" },
  SuperNetworkIcon: { category: "Product" },
  SupersimIcon: { category: "Product" },
  SyncIcon: { category: "Product" },
  TaskrouterIcon: { category: "Product" },
  TrustOnboardIcon: { category: "Product" },
  TwilioApiForWhatsappIcon: { category: "Product" },
  TwilioForSalesforceIcon: { category: "Product" },
  TwoFactorAuthenticationIcon: { category: "Product" },
  UnderstandIcon: { category: "Product" },
  VerifiedByIcon: { category: "Product" },
  VerifyIcon: { category: "Product" },

  /******************
   * Sendgrid Icons *
   ******************/
  // Content
  BulletCheckIcon: { category: "Content" },
  BulletMinusIcon: { category: "Content" },
  // Decorative
  AbTestingIcon: { category: "Decorative" },
  AutomationIcon: { category: "Decorative" },
  DesignIcon: { category: "Decorative" },
  EmailApiIcon: { category: "Decorative" },
  EmailIcon: { category: "Decorative" },
  ExpertServicesIcon: { category: "Decorative" },
  ListIcon: { category: "Decorative" },
  MarketingIcon: { category: "Decorative" },
  SignUpIcon: { category: "Decorative" },
  StatsIcon: { category: "Decorative" },
  TemplatesIcon: { category: "Decorative" },
  TestingIcon: { category: "Decorative" },
};

// export const sendgridIconMetadata: iconMetadataType = {
//   // Action
//   ChevronDownIcon: { category: "Action" },
//   ChevronUpIcon: { category: "Action" },
//   CloseIcon: { category: "Action" },
//   // Content
//   BulletCheckIcon: { category: "Content" },
//   BulletMinusIcon: { category: "Content" },
//   CheckIcon: { category: "Content" },
//   // Decorative
//   AbTestingIcon: { category: "Decorative" },
//   AutomationIcon: { category: "Decorative" },
//   ChartIcon: { category: "Decorative" },
//   CloudIcon: { category: "Decorative" },
//   DesignIcon: { category: "Decorative" },
//   EmailApiIcon: { category: "Decorative" },
//   EmailIcon: { category: "Decorative" },
//   ExpertServicesIcon: { category: "Decorative" },
//   ListIcon: { category: "Decorative" },
//   MarketingIcon: { category: "Decorative" },
//   SignUpIcon: { category: "Decorative" },
//   StatsIcon: { category: "Decorative" },
//   TemplatesIcon: { category: "Decorative" },
//   TestingIcon: { category: "Decorative" },
// };
