npmScopes:
  twilio-labs:
    npmAlwaysAuth: true
    npmAuthToken: ${GH_TOKEN:-""}
    npmRegistryServer: "https://npm.pkg.github.com"

changesetIgnorePatterns:
  - "**/*.test.{js,ts,tsx}"
  - "**/*.stories.{ts,tsx}"

defaultSemverRangePrefix: ""

packageExtensions:
  "@diez/cli-core@*":
    dependencies:
      "@types/node": "*"
      core-js: "*"
    peerDependencies:
      typescript: "*"
    optionalDependencies:
      "@diez/compiler-core": "*"
      "@diez/extractors": "*"
      "@diez/extractors-core": "*"
      "@diez/start": "*"
      "@diez/stdlib": "*"
      "@diez/targets": "*"
  "@diez/compiler-core@*":
    dependencies:
      "@diez/stdlib": "*"
      "@types/node": "*"
  "@diez/createproject@*":
    peerDependencies:
      typescript: "*"
  "@diez/extractors-core@*":
    peerDependencies:
      typescript: "*"
  "@diez/extractors@*":
    peerDependencies:
      typescript: "*"
  "@diez/generation@*":
    peerDependencies:
      typescript: "*"
  "@diez/generators@*":
    peerDependencies:
      typescript: "*"
  "@diez/start@*":
    peerDependencies:
      typescript: "*"
  "@diez/stdlib@*":
    peerDependencies:
      typescript: "*"
  "@diez/targets@*":
    peerDependencies:
      typescript: "*"
  "@docusaurus/core@*":
    peerDependencies:
      "@docusaurus/preset-classic": "*"
    peerDependenciesMeta:
      "@docusaurus/preset-classic":
        optional: true
  "@docusaurus/mdx-loader@*":
    dependencies:
      webpack: ^4.0.0 || ^5.0.0
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/module-type-aliases@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@docusaurus/plugin-google-analytics@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-google-gtag@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@docusaurus/plugin-sitemap@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@emotion/core@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  "@theme-ui/theme-provider@*":
    peerDependencies:
      "@theme-ui/css": "*"
      react: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/jest-axe@*":
    peerDependencies:
      jest: "*"
  "@types/mdx-js__react@*":
    peerDependencies:
      react: "*"
  "@types/react-color@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react-test-renderer@*":
    peerDependencies:
      react: "*"
  "@types/reactcss@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
      react-is: "*"
  diez@*:
    peerDependencies:
      typescript: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"
  package-json@*:
    dependencies:
      "@types/node": "*"
  react-color@*:
    peerDependencies:
      react: "*"
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: "*"
  react-live@*:
    dependencies:
      "@philpl/buble": "*"
    peerDependencies:
      react: "*"
      react-dom: "*"
  reakit-system@*:
    peerDependencies:
      "@types/react": "*"
  reakit-utils@*:
    peerDependencies:
      "@types/react": "*"
  reakit-warning@*:
    peerDependencies:
      "@types/react": "*"
      react-dom: "*"
  reakit@*:
    peerDependencies:
      "@types/react": "*"
  styled-components@*:
    peerDependencies:
      react-is: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.3.1.cjs
