changesetBaseRefs:
  - main
  - origin/main

changesetIgnorePatterns:
  - "**/*.test.{js,ts,tsx}"
  - "**/*.stories.{ts,tsx}"
  - website/**/*
  - configs/**/*

defaultSemverRangePrefix: ""

npmScopes:
  twilio-labs:
    npmAlwaysAuth: true
    npmAuthToken: '${NPM_TOKEN:-""}'
    npmRegistryServer: "https://registry.npmjs.org"

packageExtensions:
  "@emotion/core@*":
    peerDependencies:
      react: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      typescript: "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      typescript: "*"
  "@storybook/core@*":
    peerDependencies:
      typescript: "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/jest-axe@*":
    peerDependencies:
      jest: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
      react-is: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"
  gatsby-plugin-image@*:
    dependencies:
      "@babel/template": ^7.12.13
  gatsby-plugin-mdx@*:
    peerDependencies:
      gatsby-remark-images: "*"
  gatsby@*:
    peerDependencies:
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  package-json@*:
    dependencies:
      "@types/node": "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  react-live@*:
    dependencies:
      "@philpl/buble": "*"
    peerDependencies:
      react: "*"
      react-dom: "*"
  reakit-system@*:
    peerDependencies:
      "@types/react": "*"
  reakit-utils@*:
    peerDependencies:
      "@types/react": "*"
  reakit-warning@*:
    peerDependencies:
      "@types/react": "*"
      react-dom: "*"
  reakit@*:
    peerDependencies:
      "@types/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-3.0.0-rc.6.cjs
