changesetBaseRefs:
  - "main"
  - "origin/main"

changesetIgnorePatterns:
  - "**/*.test.{js,ts,tsx}"
  - "**/*.stories.{ts,tsx}"

defaultSemverRangePrefix: ""

npmScopes:
  twilio-labs:
    npmAlwaysAuth: true
    npmAuthToken: '${GH_TOKEN:-""}'
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@docusaurus/core@*":
    peerDependencies:
      "@docusaurus/preset-classic": "*"
      typescript: "*"
    peerDependenciesMeta:
      "@docusaurus/preset-classic":
        optional: true
      typescript:
        optional: true
  "@docusaurus/module-type-aliases@*":
    peerDependencies:
      "@types/react": "*"
      react: "*"
  "@emotion/core@*":
    peerDependencies:
      react: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      typescript: "*"
  "@storybook/addon-essentials@*":
    peerDependencies:
      typescript: "*"
  "@storybook/core@*":
    peerDependencies:
      typescript: "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/jest-axe@*":
    peerDependencies:
      jest: "*"
  "@types/react-color@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/reactcss@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
      react-is: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"
  "gatsby@*":
    peerDependencies:
      typescript: "*"
    peerDependenciesMeta:
      typescript:
        optional: true
  "gatsby-plugin-image@*":
    dependencies:
      "@babel/template": "^7.12.13"
  package-json@*:
    dependencies:
      "@types/node": "*"
  react-dev-utils@*:
    peerDependencies:
      typescript: "*"
      webpack: "*"
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: "*"
  react-live@*:
    dependencies:
      "@philpl/buble": "*"
    peerDependencies:
      react: "*"
      react-dom: "*"
  reakit-system@*:
    peerDependencies:
      "@types/react": "*"
  reakit-utils@*:
    peerDependencies:
      "@types/react": "*"
  reakit-warning@*:
    peerDependencies:
      "@types/react": "*"
      react-dom: "*"
  reakit@*:
    peerDependencies:
      "@types/react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.4.1.cjs
