npmScopes:
  twilio-labs:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "@diez/cli-core@*":
    dependencies:
      "@types/node": "*"
      core-js: "*"
    peerDependencies:
      typescript: "*"
    optionalDependencies:
      "@diez/compiler-core": "*"
      "@diez/extractors": "*"
      "@diez/extractors-core": "*"
      "@diez/start": "*"
      "@diez/stdlib": "*"
      "@diez/targets": "*"
  "@diez/compiler-core@*":
    dependencies:
      "@diez/stdlib": "*"
      "@types/node": "*"
  "@diez/createproject@*":
    peerDependencies:
      typescript: "*"
  "@diez/extractors-core@*":
    peerDependencies:
      typescript: "*"
  "@diez/extractors@*":
    peerDependencies:
      typescript: "*"
  "@diez/generation@*":
    peerDependencies:
      typescript: "*"
  "@diez/generators@*":
    peerDependencies:
      typescript: "*"
  "@diez/start@*":
    peerDependencies:
      typescript: "*"
  "@diez/stdlib@*":
    peerDependencies:
      typescript: "*"
  "@diez/targets@*":
    peerDependencies:
      typescript: "*"
  "@emotion/core@*":
    peerDependencies:
      react: "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      "@types/react": "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  "@theme-ui/theme-provider@*":
    peerDependencies:
      "@theme-ui/css": "*"
      react: "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/react-color@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/react-test-renderer@*":
    peerDependencies:
      react: "*"
  "@types/reactcss@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
      react-is: "*"
  "@types/theme-ui@*":
    peerDependencies:
      react: "*"
  "@types/theme-ui__components@*":
    peerDependencies:
      react: "*"
  diez@*:
    peerDependencies:
      typescript: "*"
  docz-core@*:
    dependencies:
      cross-spawn: "*"
      opn: "*"
      tslib: "*"
  docz@*:
    dependencies:
      tslib: "*"
      "@types/react": "*"
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      "@babel/types": "*"
      "@theme-ui/css": "*"
      babel-plugin-export-metadata: "*"
      typescript: "*"
    optionalDependencies:
      eslint: ^6.0.0
      eslint-loader: ^3.0.2
      webpack: "*"
  eslint-module-utils@*:
    peerDependencies:
      eslint: "*"
      eslint-import-resolver-node: "*"
  gatsby-plugin-compile-es6-packages@*:
    peerDependencies:
      "@babel/preset-env": "*"
  gatsby-plugin-mdx@*:
    peerDependencies:
      "@emotion/core": "*"
      react: "*"
    optionalDependencies:
      jest: "*"
      react-test-renderer: "*"
  gatsby-plugin-react-helmet-async@*:
    optionalDependencies:
      eslint-plugin-promise: "*"
  gatsby-plugin-root-import@*:
    optionalDependencies:
      concurrently: "*"
      prettier: "*"
  gatsby-plugin-typescript@*:
    peerDependencies:
      gatsby: "*"
  gatsby-theme-docz@*:
    peerDependencies:
      "@babel/core": "*"
      "@babel/preset-env": "*"
      "@babel/types": "*"
      "@theme-ui/css": "*"
      docz: "*"
      docz-core: "*"
  gatsby@*:
    dependencies:
      react-refresh: "*"
      babel-plugin-export-metadata: "*"
    optionalDependencies:
      typescript: "*"
      "@babel/types": "*"
      "@types/react": "*"
  package-json@*:
    dependencies:
      "@types/node": "*"
  react-color@*:
    peerDependencies:
      react: "*"
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: "*"
  react-live@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  rehype-docz@*:
    peerDependencies:
      react: "*"
      react-dom: "*"
  styled-components@*:
    peerDependencies:
      react-is: "*"
  theme-ui@*:
    peerDependencies:
      "@theme-ui/css": "*"
      react: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-typescript.cjs
    spec: "@yarnpkg/plugin-typescript"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
