npmScopes:
  twilio-labs:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "react-docgen-typescript-loader@*":
    peerDependencies:
      "webpack": "*"
  "react-docgen-typescript-plugin@*":
    peerDependencies:
      "webpack": "*"
  "react-color@*":
    peerDependencies:
      "react": "*"
  "@storybook/react@*":
    peerDependencies:
      "typescript": "*"
  "eslint-module-utils@*":
    peerDependencies:
      "eslint-import-resolver-node": "*"
      "eslint": "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      "@types/react": "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/react-color@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/reactcss@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
  "@types/react-test-renderer@*":
    peerDependencies:
      react: "*"

  # Diez Dependencies
  "@diez/cli-core@*":
    dependencies:
      "@diez/compiler-core": "*"
      "@diez/prefabs": "*"
      "@diez/start": "*"
      "@diez/stdlib": "*"
      "@diez/targets": "*"
      "@diez/extractors": "*"
      "core-js": "*"
      "diez": "*"
      "typescript": "*"
  "@diez/compiler-core@*":
    dependencies:
      "@diez/stdlib": "*"

  # Docz / Gatsby Dependencies
  "gatsby@*":
    dependencies:
      "react-refresh": "*"
    peerDependencies:
      "@babel/types": "*"
      "typescript": "*"
      "babel-plugin-export-metadata": "*"
  "docz@*":
    dependencies:
      "tslib": "*"
    optionalDependencies:
      "eslint-loader": "^3.0.2"
      "eslint": "^6.0.0"
      "webpack": "*"
    peerDependencies:
      "typescript": "*"
      "@babel/core": "*"
      "@babel/types": "*"
      "@babel/preset-env": "*"
      "babel-plugin-export-metadata": "*"
  "docz-core@*":
    dependencies:
      "cross-spawn": "*"
      "tslib": "*"
      "opn": "*"
  "gatsby-theme-docz@*":
    peerDependencies:
      "docz": "*"
      "docz-core": "*"
      "@babel/core": "*"
      "@babel/types": "*"
      "@babel/preset-env": "*"
  "gatsby-plugin-typescript@*":
    peerDependencies:
      "gatsby": "*"
  "gatsby-plugin-compile-es6-packages@*":
    peerDependencies:
      "@babel/preset-env": "*"
  "gatsby-plugin-mdx@*":
    optionalDependencies:
      "react-test-renderer": "*"
      "jest": "*"
    peerDependencies:
      "@emotion/core": "*"
      "react": "*"
  "gatsby-plugin-react-helmet-async@*":
    optionalDependencies:
      "eslint-plugin-promise": "*"
  "gatsby-plugin-root-import@*":
    optionalDependencies:
      "prettier": "*"
      "concurrently": "*"
  "react-live@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "rehype-docz@*":
    peerDependencies:
      "react": "*"
      "react-dom": "*"
  "@emotion/core@*":
    peerDependencies:
      "react": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs
