npmScopes:
  twilio-labs:
    npmRegistryServer: "https://npm.pkg.github.com"

packageExtensions:
  "react-docgen-typescript-loader@*":
    peerDependencies:
      "webpack": "*"
  "react-docgen-typescript-plugin@*":
    peerDependencies:
      "webpack": "*"
  "react-color@*":
    peerDependencies:
      "react": "*"
  "@storybook/react@*":
    peerDependencies:
      "typescript": "*"
  "eslint-module-utils@*":
    peerDependencies:
      "eslint-import-resolver-node": "*"
      "eslint": "*"
  "@storybook/addon-knobs@*":
    peerDependencies:
      "@types/react": "*"
  "@types/hoist-non-react-statics@*":
    peerDependencies:
      react: "*"
  "@types/react-color@*":
    peerDependencies:
      react: "*"
  "@types/react-dom@*":
    peerDependencies:
      react: "*"
  "@types/reactcss@*":
    peerDependencies:
      react: "*"
  "@types/styled-components@*":
    peerDependencies:
      react: "*"
  "@types/react-test-renderer@*":
    peerDependencies:
      react: "*"
  "@diez/cli-core@*":
    dependencies:
      "@diez/compiler-core": "*"
      "@diez/prefabs": "*"
      "@diez/start": "*"
      "@diez/stdlib": "*"
      "@diez/targets": "*"
      "@diez/extractors": "*"
      "core-js": "*"
      "diez": "*"
      "typescript": "*"
  "@diez/compiler-core@*":
    dependencies:
      "@diez/stdlib": "*"
  "docz-core@*":
    dependencies:
      "cross-spawn": "*"
      "tslib": "*"
      "opn": "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.1.1.cjs

nodeLinker: node-modules
