module.exports = {
  matchDesignSystem: {
    ["Getting Started"]: [
      "getting-started",
      "getting-started/design",
      "getting-started/develop",
    ],
    ["Design Tokens"]: ["design-tokens/introduction", "design-tokens/tokens"],
    ["Foundation"]: ["foundation/icons-list"],
    ["Components"]: [
      "components/anchor",
      "components/button",
      "components/card",
      "components/checkbox",
      "components/code",
      "components/grid",
      "components/heading",
      "components/icon",
      "components/input",
      "components/logo",
      "components/paragraph",
      "components/radio-group",
      "components/separator",
      "components/snippet",
      "components/textarea",
      "components/truncate",
      "components/visually-hidden",
    ],
    ["Instapage"]: [
      "instapage/how-to-use-blocks",
      "instapage/call-out",
      "instapage/card-list",
      "instapage/cta-section",
      "instapage/customer-quote",
      "instapage/features",
      "instapage/features-with-image",
      "instapage/features-with-paragraph",
      "instapage/hero-with-illustration",
      "instapage/hero-without-illustration",
      "instapage/intro",
      "instapage/ittb-call-out",
      "instapage/logo-bar",
      "instapage/overview",
      "instapage/platform-benefits",
      "instapage/pricing",
      "instapage/technical-resources",
    ],
  },
};
