name: Chromatic

on: push

jobs:
  chromatic:
    runs-on: ubuntu-latest
    if: "!contains(github.event.head_commit.message, 'chore(release): publish')"
    strategy:
      matrix:
        node-version: [12.18.x]

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0 # Required to retrieve git history
      - uses: chromaui/action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          projectToken: ${{ secrets.CHROMATIC_PROJECT_TOKEN }}
