name: Publish Website

on: pull_request

jobs:
  build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - name: Install dependencies
        run: yarn install
      - name: Build Tokens
        run: yarn build:tokens
      - name: Deploy to GH Pages
        run: yarn deploy:website
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
