name: Publish

on:
  push:
    branches:
      - main

jobs:
  website:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap.yml
      - name: Configure Git
        run: |
          git config user.name MatchBot
          git config user.email match@twilio.com
      - name: Deploy to GH Pages
        run: yarn workspace @twilio-labs/match-website deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}

  pypi:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap.yml
      - uses: actions/setup-python@v2
        with:
          python-version: "3.x"
      - name: Install Python dependencies
        run: python -m pip install --upgrade pip setuptools wheel twine
      - name: Build tokens
        run: yarn workspace @twilio-labs/match_tokens_py build
      - name: Publish to PyPI
        working-directory: "packages/match-tokens/py"
        env:
          TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
          TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
        run: |
          python setup.py sdist bdist_wheel
          twine upload --non-interactive --repository pypi dist/*
