name: PR Checks

on: pull_request

jobs:
  build_and_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/bootstrap.yml
      - name: Run type checker
        run: yarn type-check
      - name: Run tests
        run: yarn test:ci
