name: PR Checks

on: pull_request

jobs:
  build_and_tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2-beta
        with:
          node-version: "12"
      - run: |
          git config user.name MatchBot
          git config user.email match@twilio.com
      - name: Install dependencies
        run: yarn install
      - name: Build Tokens
        run: yarn build:tokens
      - name: Run tests
        run: yarn test:ci
